import { Restaurant, FoodItem, Coupon } from '../types';
import { db } from '../lib/firebase';
import { collection, getDocs, writeBatch, doc } from 'firebase/firestore';

export const INITIAL_RESTAURANTS: Restaurant[] = [
  {
    restaurantId: 'rest-1',
    sellerId: 'seller-demo-1',
    name: 'The Royal Biryani Durbar',
    logo: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=160&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=1200&auto=format&fit=crop&q=80',
    description: 'Slow-cooked Dum Biryanis, tender Kebabs, and authentic Mughlai curries infused with royal saffron & spices.',
    address: '42 Nizam Heritage Enclave, Central Avenue',
    cuisine: ['Biryani', 'Mughlai', 'North Indian', 'Kebabs'],
    rating: 4.8,
    reviewsCount: 1420,
    status: 'open',
    deliveryTime: '30-40 min',
    minOrder: 199,
    openingHours: '11:00 AM - 11:30 PM',
    phone: '+91 98765 43210',
    createdAt: new Date().toISOString(),
    isPopular: true,
    isTopRated: true,
  },
  {
    restaurantId: 'rest-2',
    sellerId: 'seller-demo-2',
    name: 'Artisan Crust Pizza Co.',
    logo: 'https://images.unsplash.com/photo-1590947132387-155cc02f3212?w=160&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=1200&auto=format&fit=crop&q=80',
    description: 'Authentic woodfired Neapolitan sourdough pizzas topped with Fior di Latte mozzarella & San Marzano tomatoes.',
    address: '88 Baker Street, Piazza Market',
    cuisine: ['Pizza', 'Italian', 'Fast Food', 'Desserts'],
    rating: 4.7,
    reviewsCount: 980,
    status: 'open',
    deliveryTime: '25-35 min',
    minOrder: 249,
    openingHours: '11:30 AM - 11:00 PM',
    phone: '+91 98765 43211',
    createdAt: new Date().toISOString(),
    isPopular: true,
    isTopRated: true,
  },
  {
    restaurantId: 'rest-3',
    sellerId: 'seller-demo-3',
    name: 'The Gourmet Smash Burger',
    logo: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=160&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=1200&auto=format&fit=crop&q=80',
    description: 'Crispy-edged prime smashed patties, butter toasted brioche buns, melted cheddar, and secret signature relish.',
    address: '15 Downtown Boulevard, City Center',
    cuisine: ['Burger', 'Fast Food', 'Beverages', 'Snacks'],
    rating: 4.6,
    reviewsCount: 840,
    status: 'open',
    deliveryTime: '20-30 min',
    minOrder: 149,
    openingHours: '12:00 PM - 12:00 AM',
    phone: '+91 98765 43212',
    createdAt: new Date().toISOString(),
    isPopular: true,
    isTopRated: false,
  },
  {
    restaurantId: 'rest-4',
    sellerId: 'seller-demo-4',
    name: 'Golden Dragon Dimsum & Wok',
    logo: 'https://images.unsplash.com/photo-1541696432-82c6da8ce7bf?w=160&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?w=1200&auto=format&fit=crop&q=80',
    description: 'Sizzling wok stir-fries, handcrafted crystal dim sums, Hakka noodles, and authentic Sichuan spicy delights.',
    address: '24 Oriental Lane, Lakeview Square',
    cuisine: ['Chinese', 'Asian', 'Noodles', 'Fast Food'],
    rating: 4.5,
    reviewsCount: 710,
    status: 'open',
    deliveryTime: '30-40 min',
    minOrder: 199,
    openingHours: '12:30 PM - 10:45 PM',
    phone: '+91 98765 43213',
    createdAt: new Date().toISOString(),
    isPopular: false,
    isTopRated: true,
  },
  {
    restaurantId: 'rest-5',
    sellerId: 'seller-demo-5',
    name: 'Dakshin Express Delights',
    logo: 'https://images.unsplash.com/photo-1610192244261-3f33de3f55e4?w=160&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=1200&auto=format&fit=crop&q=80',
    description: 'Crispy golden Ghee Roast Dosas, fluffy Steamed Idlis, aromatic Filter Coffee, and freshly ground coconut chutneys.',
    address: '7 Temple Road, Green Valley',
    cuisine: ['South Indian', 'Indian', 'Beverages', 'Breakfast'],
    rating: 4.9,
    reviewsCount: 1650,
    status: 'open',
    deliveryTime: '20-25 min',
    minOrder: 99,
    openingHours: '07:00 AM - 10:00 PM',
    phone: '+91 98765 43214',
    createdAt: new Date().toISOString(),
    isPopular: true,
    isTopRated: true,
  },
  {
    restaurantId: 'rest-6',
    sellerId: 'seller-demo-6',
    name: 'Dolce Vita Patisserie & Gelato',
    logo: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=160&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=1200&auto=format&fit=crop&q=80',
    description: 'Heavenly Belgian chocolate lava cakes, handcrafted Italian tiramisu, artisan macarons, and rich creamy shakes.',
    address: '5 Sunshine Court, High Street',
    cuisine: ['Desserts', 'Beverages', 'Bakery'],
    rating: 4.8,
    reviewsCount: 620,
    status: 'open',
    deliveryTime: '20-30 min',
    minOrder: 150,
    openingHours: '10:00 AM - 11:30 PM',
    phone: '+91 98765 43215',
    createdAt: new Date().toISOString(),
    isPopular: true,
    isTopRated: true,
  },
];

export const INITIAL_FOOD_ITEMS: FoodItem[] = [
  // Biryani (Rest 1)
  {
    foodId: 'food-1',
    restaurantId: 'rest-1',
    sellerId: 'seller-demo-1',
    name: 'Hyderabadi Dum Chicken Biryani',
    description: 'Long-grain basmati rice cooked on slow dum with succulent tender chicken, saffron, fried onions & royal spices. Served with Mirchi ka Salan & Raita.',
    price: 349,
    discountPrice: 299,
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800&auto=format&fit=crop&q=80',
    category: 'Biryani',
    foodType: 'non-veg',
    availability: 'active',
    isBestseller: true,
    rating: 4.9,
    ratingCount: 520,
    createdAt: new Date().toISOString(),
  },
  {
    foodId: 'food-2',
    restaurantId: 'rest-1',
    sellerId: 'seller-demo-1',
    name: 'Royal Shahi Paneer Tikka Biryani',
    description: 'Rich layers of fragrant basmati rice tossed with chargrilled marinated cottage cheese, saffron milk, mint leaves and roasted cashews.',
    price: 319,
    discountPrice: 279,
    image: 'https://images.unsplash.com/photo-1642821373181-696a54913e93?w=800&auto=format&fit=crop&q=80',
    category: 'Biryani',
    foodType: 'veg',
    availability: 'active',
    isBestseller: true,
    rating: 4.7,
    ratingCount: 310,
    createdAt: new Date().toISOString(),
  },
  {
    foodId: 'food-3',
    restaurantId: 'rest-1',
    sellerId: 'seller-demo-1',
    name: 'Lucknowi Mutton Galouti Kebab (4 pcs)',
    description: 'Melt-in-mouth spiced minced lamb patties infused with raw papaya, rose water, and 32 hand-ground royal spices.',
    price: 429,
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=800&auto=format&fit=crop&q=80',
    category: 'Indian',
    foodType: 'non-veg',
    availability: 'active',
    isBestseller: false,
    rating: 4.8,
    ratingCount: 190,
    createdAt: new Date().toISOString(),
  },
  {
    foodId: 'food-4',
    restaurantId: 'rest-1',
    sellerId: 'seller-demo-1',
    name: 'Dal Makhani Bukhara Style',
    description: 'Slow-simmered black lentils over charcoal embers for 24 hours with fresh cream and clarified white butter.',
    price: 269,
    discountPrice: 239,
    image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800&auto=format&fit=crop&q=80',
    category: 'Indian',
    foodType: 'veg',
    availability: 'active',
    isBestseller: true,
    rating: 4.8,
    ratingCount: 420,
    createdAt: new Date().toISOString(),
  },

  // Pizza (Rest 2)
  {
    foodId: 'food-5',
    restaurantId: 'rest-2',
    sellerId: 'seller-demo-2',
    name: 'Woodfired Margherita Burrata',
    description: 'San Marzano tomato sauce, fresh buffalo mozzarella, aromatic sweet basil leaves, virgin olive oil, topped with creamy artisanal burrata.',
    price: 449,
    discountPrice: 399,
    image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800&auto=format&fit=crop&q=80',
    category: 'Pizza',
    foodType: 'veg',
    availability: 'active',
    isBestseller: true,
    rating: 4.9,
    ratingCount: 460,
    createdAt: new Date().toISOString(),
  },
  {
    foodId: 'food-6',
    restaurantId: 'rest-2',
    sellerId: 'seller-demo-2',
    name: 'Smoked Pepperoni & Hot Honey',
    description: 'Crispy cupping pepperoni, mozzarella blend, pickled jalapenos, drizzled with spicy infused wildflower honey.',
    price: 529,
    discountPrice: 479,
    image: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?w=800&auto=format&fit=crop&q=80',
    category: 'Pizza',
    foodType: 'non-veg',
    availability: 'active',
    isBestseller: true,
    rating: 4.9,
    ratingCount: 580,
    createdAt: new Date().toISOString(),
  },
  {
    foodId: 'food-7',
    restaurantId: 'rest-2',
    sellerId: 'seller-demo-2',
    name: 'Four Cheese Truffle Mushroom',
    description: 'Mozzarella, Gorgonzola, aged Parmesan, Ricotta, wild sauteed portobello mushrooms, drizzled with white truffle essence.',
    price: 499,
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&auto=format&fit=crop&q=80',
    category: 'Pizza',
    foodType: 'veg',
    availability: 'active',
    isBestseller: false,
    rating: 4.6,
    ratingCount: 220,
    createdAt: new Date().toISOString(),
  },
  {
    foodId: 'food-8',
    restaurantId: 'rest-2',
    sellerId: 'seller-demo-2',
    name: 'Garlic Parmesan Herb Dough Twists',
    description: 'Warm, oven-baked sourdough twists smothered in garlic herb butter, grated Parmigiano, served with warm marinara dipping sauce.',
    price: 189,
    discountPrice: 159,
    image: 'https://images.unsplash.com/photo-1541745537411-b8046dc6d66c?w=800&auto=format&fit=crop&q=80',
    category: 'Snacks',
    foodType: 'veg',
    availability: 'active',
    isBestseller: false,
    rating: 4.7,
    ratingCount: 180,
    createdAt: new Date().toISOString(),
  },

  // Burger (Rest 3)
  {
    foodId: 'food-9',
    restaurantId: 'rest-3',
    sellerId: 'seller-demo-3',
    name: 'Double Truffle Cheeseburger',
    description: 'Two smashed tender beef/chicken patties, double aged cheddar, caramelized shallots, crispy onions, truffle aioli on brioche.',
    price: 369,
    discountPrice: 329,
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&auto=format&fit=crop&q=80',
    category: 'Burger',
    foodType: 'non-veg',
    availability: 'active',
    isBestseller: true,
    rating: 4.8,
    ratingCount: 640,
    createdAt: new Date().toISOString(),
  },
  {
    foodId: 'food-10',
    restaurantId: 'rest-3',
    sellerId: 'seller-demo-3',
    name: 'Crispy Nashville Hot Chicken Burger',
    description: 'Buttermilk fried chicken breast tossed in cayenne hot sauce, creamy coleslaw, dill pickle slices on toasted sesame bun.',
    price: 319,
    discountPrice: 289,
    image: 'https://images.unsplash.com/photo-1625813506062-0aeb1d7a094b?w=800&auto=format&fit=crop&q=80',
    category: 'Burger',
    foodType: 'non-veg',
    availability: 'active',
    isBestseller: true,
    rating: 4.7,
    ratingCount: 410,
    createdAt: new Date().toISOString(),
  },
  {
    foodId: 'food-11',
    restaurantId: 'rest-3',
    sellerId: 'seller-demo-3',
    name: 'Avocado Crisp Halloumi Burger',
    description: 'Golden fried halloumi cheese block, sliced Hass avocado, sun-dried tomato spread, baby rocket leaves, herb mayo.',
    price: 299,
    image: 'https://images.unsplash.com/photo-1584947897591-a98e87498c4d?w=800&auto=format&fit=crop&q=80',
    category: 'Burger',
    foodType: 'veg',
    availability: 'active',
    isBestseller: false,
    rating: 4.6,
    ratingCount: 195,
    createdAt: new Date().toISOString(),
  },
  {
    foodId: 'food-12',
    restaurantId: 'rest-3',
    sellerId: 'seller-demo-3',
    name: 'Cheddar Bacon Loaded Curly Fries',
    description: 'Crispy seasoned curly potato fries drenched in warm cheddar cheese sauce, bacon crisps, and chopped spring onions.',
    price: 199,
    discountPrice: 169,
    image: 'https://images.unsplash.com/photo-1585109649139-366815a0d713?w=800&auto=format&fit=crop&q=80',
    category: 'Fast Food',
    foodType: 'non-veg',
    availability: 'active',
    isBestseller: true,
    rating: 4.8,
    ratingCount: 320,
    createdAt: new Date().toISOString(),
  },

  // Chinese (Rest 4)
  {
    foodId: 'food-13',
    restaurantId: 'rest-4',
    sellerId: 'seller-demo-4',
    name: 'Steamed Crystal Chicken Dim Sums (6 pcs)',
    description: 'Hand-pleated translucent dumplings filled with minced ginger chicken and scallions, served with spicy burnt garlic chili oil.',
    price: 289,
    discountPrice: 249,
    image: 'https://images.unsplash.com/photo-1541696432-82c6da8ce7bf?w=800&auto=format&fit=crop&q=80',
    category: 'Chinese',
    foodType: 'non-veg',
    availability: 'active',
    isBestseller: true,
    rating: 4.8,
    ratingCount: 380,
    createdAt: new Date().toISOString(),
  },
  {
    foodId: 'food-14',
    restaurantId: 'rest-4',
    sellerId: 'seller-demo-4',
    name: 'Spicy Sichuan Kung Pao Noodles',
    description: 'Wok-tossed noodles in fiery Sichuan peppercorn sauce, crunchy bell peppers, toasted peanuts, and aromatic garlic.',
    price: 249,
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800&auto=format&fit=crop&q=80',
    category: 'Chinese',
    foodType: 'veg',
    availability: 'active',
    isBestseller: false,
    rating: 4.5,
    ratingCount: 210,
    createdAt: new Date().toISOString(),
  },

  // South Indian (Rest 5)
  {
    foodId: 'food-15',
    restaurantId: 'rest-5',
    sellerId: 'seller-demo-5',
    name: 'Mylapore Ghee Podi Masala Dosa',
    description: 'Super-crisp golden fermented crepe roasted in aromatic country butter ghee, spiced with gunpowder masala, stuffed with spiced potato mash.',
    price: 189,
    discountPrice: 159,
    image: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=800&auto=format&fit=crop&q=80',
    category: 'South Indian',
    foodType: 'veg',
    availability: 'active',
    isBestseller: true,
    rating: 4.9,
    ratingCount: 920,
    createdAt: new Date().toISOString(),
  },
  {
    foodId: 'food-16',
    restaurantId: 'rest-5',
    sellerId: 'seller-demo-5',
    name: 'Steamed Button Idli & Crispy Medu Vada Combo',
    description: 'Piping hot mini rice idlis and crispy urad dal vada served immersed in piping hot traditional Drumstick Sambar with three coconut chutneys.',
    price: 149,
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=800&auto=format&fit=crop&q=80',
    category: 'South Indian',
    foodType: 'veg',
    availability: 'active',
    isBestseller: true,
    rating: 4.8,
    ratingCount: 540,
    createdAt: new Date().toISOString(),
  },

  // Desserts & Beverages (Rest 6)
  {
    foodId: 'food-17',
    restaurantId: 'rest-6',
    sellerId: 'seller-demo-6',
    name: 'Belgian Molten Choco Lava Soufflé',
    description: 'Warm cocoa cake with an oozy warm ganache center made with 70% Callebaut dark chocolate. Dusted with powdered sugar.',
    price: 219,
    discountPrice: 189,
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=800&auto=format&fit=crop&q=80',
    category: 'Desserts',
    foodType: 'veg',
    availability: 'active',
    isBestseller: true,
    rating: 4.9,
    ratingCount: 680,
    createdAt: new Date().toISOString(),
  },
  {
    foodId: 'food-18',
    restaurantId: 'rest-6',
    sellerId: 'seller-demo-6',
    name: 'Classic Venetian Mascarpone Tiramisu',
    description: 'Espresso-soaked Savoiardi ladyfingers layered with whipped sweet mascarpone cream and dusted with raw Dutch cocoa.',
    price: 259,
    discountPrice: 229,
    image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=800&auto=format&fit=crop&q=80',
    category: 'Desserts',
    foodType: 'veg',
    availability: 'active',
    isBestseller: true,
    rating: 4.8,
    ratingCount: 390,
    createdAt: new Date().toISOString(),
  },
  {
    foodId: 'food-19',
    restaurantId: 'rest-6',
    sellerId: 'seller-demo-6',
    name: 'Salted Caramel Hazelnut Milkshake',
    description: 'Blended whole milk, Italian hazelnut gelato, sea-salted caramel ribbon, whipped cream, and roasted crushed praline.',
    price: 199,
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=800&auto=format&fit=crop&q=80',
    category: 'Beverages',
    foodType: 'veg',
    availability: 'active',
    isBestseller: false,
    rating: 4.7,
    ratingCount: 260,
    createdAt: new Date().toISOString(),
  },
  {
    foodId: 'food-20',
    restaurantId: 'rest-5',
    sellerId: 'seller-demo-5',
    name: 'Madras Filter Kaapi (Double Shot)',
    description: 'Brewed fresh through traditional brass filter with chicory-infused South Indian plantation coffee beans and frothed milk.',
    price: 79,
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&auto=format&fit=crop&q=80',
    category: 'Beverages',
    foodType: 'veg',
    availability: 'active',
    isBestseller: true,
    rating: 4.9,
    ratingCount: 880,
    createdAt: new Date().toISOString(),
  }
];

export const INITIAL_COUPONS: Coupon[] = [
  {
    couponId: 'coup-1',
    code: 'FOODIE50',
    discountType: 'percentage',
    discount: 50,
    minOrder: 299,
    maxDiscount: 150,
    expiryDate: '2026-12-31',
    usageLimit: 1000,
    usedCount: 142,
    active: true,
    description: '50% OFF up to ₹150 on orders above ₹299',
  },
  {
    couponId: 'coup-2',
    code: 'WELCOME100',
    discountType: 'fixed',
    discount: 100,
    minOrder: 399,
    maxDiscount: 100,
    expiryDate: '2026-12-31',
    usageLimit: 500,
    usedCount: 89,
    active: true,
    description: 'Flat ₹100 instant discount on orders above ₹399',
  },
  {
    couponId: 'coup-3',
    code: 'FEAST20',
    discountType: 'percentage',
    discount: 20,
    minOrder: 499,
    maxDiscount: 200,
    expiryDate: '2026-12-31',
    usageLimit: 2000,
    usedCount: 310,
    active: true,
    description: '20% OFF up to ₹200 on grand feasts above ₹499',
  },
];

export const CATEGORIES = [
  {
    id: 'Pizza',
    name: 'Pizza',
    icon: '🍕',
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&auto=format&fit=crop&q=80',
    description: 'Woodfired sourdough Neapolitan pizzas with gourmet toppings and melted burrata.',
  },
  {
    id: 'Burger',
    name: 'Burger',
    icon: '🍔',
    image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=800&auto=format&fit=crop&q=80',
    description: 'Juicy prime smash patties, toasted brioche buns, and melted artisanal cheddar.',
  },
  {
    id: 'Biryani',
    name: 'Biryani',
    icon: '🥘',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800&auto=format&fit=crop&q=80',
    description: 'Slow-dum royal basmati rice cooked with fragrant saffron, ghee, and succulent meats.',
  },
  {
    id: 'Indian',
    name: 'Indian',
    icon: '🍛',
    image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800&auto=format&fit=crop&q=80',
    description: 'Rich creamy gravies, smoky tandoori kebabs, and hot buttered garlic naans.',
  },
  {
    id: 'Chinese',
    name: 'Chinese',
    icon: '🥡',
    image: 'https://images.unsplash.com/photo-1541696432-82c6da8ce7bf?w=800&auto=format&fit=crop&q=80',
    description: 'Fiery Sichuan woks, silky dim sums, crispy spring rolls, and Hakka noodles.',
  },
  {
    id: 'South Indian',
    name: 'South Indian',
    icon: '🥞',
    image: 'https://images.unsplash.com/photo-1610192244261-3f33de3f55e4?w=800&auto=format&fit=crop&q=80',
    description: 'Crispy golden ghee roast dosas, fluffy idlis, and aromatic filter coffee.',
  },
  {
    id: 'Desserts',
    name: 'Desserts',
    icon: '🍰',
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=800&auto=format&fit=crop&q=80',
    description: 'Decadent Belgian chocolate cakes, hot gulab jamuns, and Italian gelato.',
  },
  {
    id: 'Beverages',
    name: 'Beverages',
    icon: '🥤',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=800&auto=format&fit=crop&q=80',
    description: 'Refreshing cold-pressed juices, chilled thick shakes, and artisan brewed coffees.',
  },
  {
    id: 'Snacks',
    name: 'Snacks',
    icon: '🍟',
    image: 'https://images.unsplash.com/photo-1576107232684-1279f3908594?w=800&auto=format&fit=crop&q=80',
    description: 'Crispy samosas, loaded cheese nachos, golden fries, and savoury evening bites.',
  },
  {
    id: 'Fast Food',
    name: 'Fast Food',
    icon: '🌭',
    image: 'https://images.unsplash.com/photo-1561758033-d89a9ad46330?w=800&auto=format&fit=crop&q=80',
    description: 'Quick-served comfort wraps, crispy fried chicken, sandwiches, and combo platters.',
  },
];

/**
 * Initializes default restaurants, foods, and coupons in Firestore if not already populated.
 */
export async function seedFirestoreIfEmpty() {
  try {
    const restCol = collection(db, 'restaurants');
    const snap = await getDocs(restCol);
    if (!snap.empty) {
      return; // Already populated
    }

    const batch = writeBatch(db);

    // Seed restaurants
    for (const r of INITIAL_RESTAURANTS) {
      const docRef = doc(db, 'restaurants', r.restaurantId);
      batch.set(docRef, r);
    }

    // Seed foods
    for (const f of INITIAL_FOOD_ITEMS) {
      const docRef = doc(db, 'foodItems', f.foodId);
      batch.set(docRef, f);
    }

    // Seed coupons
    for (const c of INITIAL_COUPONS) {
      const docRef = doc(db, 'coupons', c.couponId);
      batch.set(docRef, c);
    }

    await batch.commit();
    console.log('Seed data successfully written to Firestore');
  } catch (error) {
    console.warn('Seed operation error (will fallback to in-memory state):', error);
  }
}

// Enhance INITIAL_FOOD_ITEMS with required fields: id, status, available, bestseller
INITIAL_FOOD_ITEMS.forEach((f) => {
  f.id = f.foodId;
  f.status = f.status || 'published';
  f.available = f.available ?? true;
  f.bestseller = f.bestseller ?? f.isBestseller ?? false;
  f.cuisine = f.cuisine || f.category;
  f.preparationTime = f.preparationTime || '20-30 min';
});
